### ISSUE TITLE
Change flow to environment-based specification

### ISSUE THREAD

**Issue by vranystepan** [AckeeDevOps/vaultier#1]
Cosmetic but perhaps breaking change. My intent is to consolidate the current format config to something like:

```yaml
environments:
  - name: production
    secrets:
      - path: secret/data/blah/production/config1
        keyMap:
          - vaultKey: vaultVariableName1
            localKey: VAR1
      - path: secret/data/blah/production/config2
        keyMap:
          - vaultKey: vaultVariableName2
            localKey: VAR2
  - name: production
    secrets:
      - path: secret/data/blah/production/config1
        keyMap:
          - vaultKey: vaultVariableName1
            localKey: VAR1
      - path: secret/data/blah/production/config2
        keyMap:
          - vaultKey: vaultVariableName2
            localKey: VAR2
  - name: local-development
    secrets:
      - path: secret/data/blah/production/config1
        keyMap:
          - vaultKey: vaultVariableName1
            localKey: VAR1
      - path: secret/data/blah/production/config2
        keyMap:
          - vaultKey: vaultVariableName2
            localKey: VAR2
```

This means that `VAULTIER_RUN_CAUSE` won't be needed anymore.
